//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursaty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoursesComment()
        {
            this.CoursesComments_Replies = new HashSet<CoursesComments_Replies>();
        }
    
        public int id { get; set; }
        public System.DateTime currDate { get; set; }
        public string comment { get; set; }
        public int userId { get; set; }
        public int courseId { get; set; }
        public int likes { get; set; }
        public int dislikes { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursesComments_Replies> CoursesComments_Replies { get; set; }
    }
}
